package flow;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or webservice), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Avaya Dialog Designer at: 2005-JUN-15  04:18:17 PM
 */
public class GoAgain extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Avaya Dialog Designer at: 2005-JUN-15  04:18:17 PM
	 */
	public GoAgain() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("End", "Default");
		next.setDebugId(709);
		return next;
	}
	
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(10);
		actions.add(new com.avaya.sce.runtime.varoperations.Divide("Score", "CorrectAnswers", false, "TotalQuestions", false).setDebugId(697));
		actions.add(new com.avaya.sce.runtime.varoperations.Multiply("Score", "Score", false, "100", true).setDebugId(698));
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("YourReportCard", "You got ", true).setDebugId(699));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("YourReportCard", "CorrectAnswers", false).setDebugId(700));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("YourReportCard", " out of ", true).setDebugId(701));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("YourReportCard", "TotalQuestions", false).setDebugId(702));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("YourReportCard", " answers correct. Your score is ", true).setDebugId(703));
		actions.add(new com.avaya.sce.runtime.varoperations.Parse("Score", "Score", ".", false).setDebugId(704));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("YourReportCard", "Score", false).setDebugId(705));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("YourReportCard", "%", true).setDebugId(706));
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "CalculateAnswer:value", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "yes", false).setDebugId(707)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("RandomNumberGenerator", "GoAgain").setDebugId(708));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		}

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
}
