package flow;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Avaya Dialog Designer at: 2005-JUL-01  06:57:33 PM
 */
public class ReCalc extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Avaya Dialog Designer at: 2005-JUL-01  06:57:33 PM
	 */
	public ReCalc() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("StartOver", "Default");
		next.setDebugId(694);
		return next;
	}
	
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(10);
		actions.add(new com.avaya.sce.runtime.varoperations.Divide("Score", "CorrectAnswers", false, "TotalQuestions", false).setDebugId(684));
		actions.add(new com.avaya.sce.runtime.varoperations.Multiply("Score", "Score", false, "100", true).setDebugId(685));
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("YourReportCard", "You got ", true).setDebugId(686));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("YourReportCard", "CorrectAnswers", false).setDebugId(687));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("YourReportCard", " out of ", true).setDebugId(688));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("YourReportCard", "TotalQuestions", false).setDebugId(689));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("YourReportCard", " answers correct. Your score is ", true).setDebugId(690));
		actions.add(new com.avaya.sce.runtime.varoperations.Parse("Score", "Score", ".", false).setDebugId(691));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("YourReportCard", "Score", false).setDebugId(692));
		actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("YourReportCard", "%", true).setDebugId(693));
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
}
