package english.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Avaya Dialog Designer at: 2005-JUN-17  04:27:59 PM
 */
public class Quit extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for Quit.
    */
    public Quit() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("voice");
        setBuiltin(false);
        setFileName("Quit.grxml");
        addColName("Column1");
		//}}END:CLASS:CONSTRUCTOR
    }

}

