package english.grammars;

/**
 * This class is generated automatically and should not be manually edited.
 * Manually edited changes will be lost when the grammar is regenerated.
 * Last generated by Avaya Dialog Designer at: 2005-JUN-08  02:10:14 PM
 */
public class QuizChoices extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for QuizChoices.
    */
    public QuizChoices() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("voice");
        setBuiltin(false);
        setFileName("QuizChoices.grxml");
        addColName("Column1");
		//}}END:CLASS:CONSTRUCTOR
    }

}

