package english.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Avaya Dialog Designer at: 2005-JUN-17  04:26:00 PM
 */
public class StartOver extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for StartOver.
    */
    public StartOver() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("voice");
        setBuiltin(false);
        setFileName("StartOver.grxml");
        addColName("Column1");
		//}}END:CLASS:CONSTRUCTOR
    }

}

