package english.grammars;

/**
 * This class is generated automatically and should not be manually edited.
 * Manually edited changes will be lost when the grammar is regenerated.
 * Last generated by Avaya Dialog Designer at: 2005-MAY-04  02:15:06 PM
 */
public class YesNo extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for YesNo.
    */
    public YesNo() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("voice");
        setBuiltin(false);
        setFileName("YesNo.grxml");
        addColName("Column1");
		//}}END:CLASS:CONSTRUCTOR
    }

}

