package english.grammars;

/**
 * This class is generated automatically and should not be manually edited.
 * Manually edited changes will be lost when the grammar is regenerated.
 * Last generated by Avaya Dialog Designer at: 2005-JUN-08  03:33:59 PM
 */
public class YourAnswerDTMF extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for YourAnswerDTMF.
    */
    public YourAnswerDTMF() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("dtmf");
        setBuiltin(true);
        setBuiltinMode("dtmf");
        setType("number");
        setOptions("");
		//}}END:CLASS:CONSTRUCTOR
    }

}

